/**
 * pap.h — C API for the Principal Agent Protocol
 *
 * Auto-generated by cbindgen from crates/pap-c/src/lib.rs.
 * Do not edit manually — regenerate with: cargo build -p pap-c
 *
 * Memory contract:
 *   - Every pap_*_generate / pap_*_new / pap_*_from_* call returns a
 *     heap-allocated handle that the caller owns and must free with the
 *     corresponding pap_*_free function.
 *   - Strings returned by any pap_* function are heap-allocated C strings
 *     and must be freed with pap_string_free().
 *   - Input strings (*const char) and byte slices (*const uint8_t) are
 *     borrowed; ownership stays with the caller.
 *
 * Error handling:
 *   - Functions that can fail return NULL (pointer) or -1 (int).
 *   - Call pap_last_error_message() to obtain a description; the returned
 *     string must be freed with pap_string_free().
 */


#ifndef PAP_H
#define PAP_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>


// Active — full scope, within TTL.
#define PAP_DECAY_ACTIVE 0

// Degraded — reduced scope, TTL within decay window, renewal pending.
#define PAP_DECAY_DEGRADED 1

// ReadOnly — TTL expired, no execution, observation only.
#define PAP_DECAY_READ_ONLY 2

// Suspended — awaiting principal review; terminal state (no renewal).
#define PAP_DECAY_SUSPENDED 3

// Initiated — token presented, awaiting verification.
#define PAP_SESSION_INITIATED 0

// Open — handshake complete, session DIDs exchanged.
#define PAP_SESSION_OPEN 1

// Executed — transaction completed within session.
#define PAP_SESSION_EXECUTED 2

// Closed — session closed, ephemeral keys discarded.
#define PAP_SESSION_CLOSED 3

typedef struct PapAdvertisement PapAdvertisement;

typedef struct PapAgentList PapAgentList;

typedef struct PapCapabilityToken PapCapabilityToken;

typedef struct PapDisclosureEntry PapDisclosureEntry;

typedef struct PapDisclosureSet PapDisclosureSet;

// Opaque handle wrapping an [`EcashBlindToken`].
typedef struct PapEcashBlindToken PapEcashBlindToken;

// Opaque handle wrapping an [`EcashMintKeypair`].
typedef struct PapEcashMintKeypair PapEcashMintKeypair;

// Opaque handle wrapping an [`EcashSpentRegistry`] (in-memory double-spend set).
typedef struct PapEcashSpentRegistry PapEcashSpentRegistry;

// Opaque handle wrapping an [`EcashToken`] (serial + unblinded signature).
typedef struct PapEcashToken PapEcashToken;

typedef struct PapMandate PapMandate;

typedef struct PapMarketplaceClient PapMarketplaceClient;

typedef struct PapMarketplaceRegistry PapMarketplaceRegistry;

typedef struct PapPrincipalKeypair PapPrincipalKeypair;

typedef struct PapReceipt PapReceipt;

// Opaque handle for a single Shamir recovery shard.
typedef struct PapRecoveryShard PapRecoveryShard;

// Opaque handle for a set of N Shamir recovery shards from one ceremony.
typedef struct PapRecoveryShardSet PapRecoveryShardSet;

typedef struct PapScope PapScope;

typedef struct PapScopeAction PapScopeAction;

typedef struct PapSession PapSession;

typedef struct PapSessionKeypair PapSessionKeypair;

// Returns the most recent error message as a heap-allocated C string,
// or NULL if no error has occurred. Caller must free with `pap_string_free`.
char *pap_last_error_message(void);

// Alias for `pap_last_error_message`.
// Returns the most recent error message as a heap-allocated C string,
// or NULL if no error has occurred. Caller must free with `pap_string_free`.
char *pap_last_error(void);

// Free a string returned by any `pap_*` function.
// # Safety
// `s` must be a pointer previously returned by a PAP function, or NULL.
void pap_string_free(char *s);

// Generate a new Ed25519 principal keypair.
struct PapPrincipalKeypair *pap_keypair_generate(void);

// Reconstruct a keypair from 32 raw secret-key bytes.
// `bytes` must point to exactly 32 bytes.
// # Safety
// `bytes` must be a valid pointer to at least `len` bytes.
struct PapPrincipalKeypair *pap_keypair_from_bytes(const uint8_t *bytes, uintptr_t len);

// Free a PapPrincipalKeypair. Passing NULL is a no-op.
// # Safety
// `kp` must be a pointer previously returned by a `pap_keypair_*` function.
void pap_keypair_free(struct PapPrincipalKeypair *kp);

// Returns the `did:key` identifier as a heap-allocated C string.
// Caller must free with `pap_string_free`.
char *pap_keypair_did(const struct PapPrincipalKeypair *kp);

// Writes the 32-byte public key into `out` (caller-allocated 32-byte buffer).
// Returns 0 on success, -1 on error.
// # Safety
// `out` must point to a buffer of at least 32 bytes.
int pap_keypair_public_bytes(const struct PapPrincipalKeypair *kp, uint8_t *out);

// Sign `msg_len` bytes at `msg`, writing the 64-byte signature into `sig_out`.
// Returns 0 on success, -1 on error.
// # Safety
// `msg` must be valid for `msg_len` bytes; `sig_out` must be at least 64 bytes.
int pap_keypair_sign(const struct PapPrincipalKeypair *kp,
                     const uint8_t *msg,
                     uintptr_t msg_len,
                     uint8_t *sig_out);

// Generate an ephemeral session keypair (single-use, not linked to principal).
struct PapSessionKeypair *pap_session_keypair_generate(void);

// Free a PapSessionKeypair. Passing NULL is a no-op.
// # Safety
// `kp` must be a pointer previously returned by `pap_session_keypair_generate`.
void pap_session_keypair_free(struct PapSessionKeypair *kp);

// Returns the ephemeral session `did:key`. Caller frees with `pap_string_free`.
char *pap_session_keypair_did(const struct PapSessionKeypair *kp);

// Extract the 32-byte Ed25519 public key from a `did:key` string.
// `out` must be a caller-allocated 32-byte buffer.
// Returns 0 on success, -1 on invalid DID.
// # Safety
// `out` must point to at least 32 bytes.
int pap_did_to_public_key_bytes(const char *did, uint8_t *out);

// Create a scope action with no object constraint.
// `action` is a Schema.org action string, e.g. `"schema:SearchAction"`.
struct PapScopeAction *pap_scope_action_new(const char *action);

// Create a scope action with an object type constraint,
// e.g. action=`"schema:ReserveAction"`, object=`"schema:Flight"`.
struct PapScopeAction *pap_scope_action_with_object(const char *action, const char *object);

// Free a PapScopeAction. Passing NULL is a no-op.
// # Safety
// `a` must be a pointer previously returned by a `pap_scope_action_*` function.
void pap_scope_action_free(struct PapScopeAction *a);

// Build a Scope from an array of PapScopeAction pointers.
// The actions are cloned; ownership of the action handles stays with the caller.
// `actions` may be NULL when `count` is 0 (produces deny-all scope).
// # Safety
// `actions` must be a valid array of `count` non-null `*const PapScopeAction` pointers.
struct PapScope *pap_scope_new(const struct PapScopeAction *const *actions, uintptr_t count);

// Create an empty (deny-all) scope.
struct PapScope *pap_scope_deny_all(void);

// Free a PapScope. Passing NULL is a no-op.
// # Safety
// `s` must be a pointer previously returned by a `pap_scope_*` function.
void pap_scope_free(struct PapScope *s);

// Returns 1 if the scope permits `action`, 0 otherwise (including on null input).
int pap_scope_permits(const struct PapScope *scope, const char *action);

// Returns 1 if every action in `child` is also in `parent` (child ⊆ parent).
// Returns 0 on any error or if the check fails.
int pap_scope_contains(const struct PapScope *parent, const struct PapScope *child);

// Create a disclosure entry describing what context an agent may share.
// `permitted` and `prohibited` are arrays of C strings of the given lengths.
// # Safety
// All pointer arrays must be valid for their given counts.
struct PapDisclosureEntry *pap_disclosure_entry_new(const char *schema_type,
                                                    const char *const *permitted,
                                                    uintptr_t permitted_count,
                                                    const char *const *prohibited,
                                                    uintptr_t prohibited_count);

// Set the `session_only` flag (non-zero = true). Returns 0 on success.
int pap_disclosure_entry_set_session_only(struct PapDisclosureEntry *e, int session_only);

// Set the `no_retention` flag (non-zero = true). Returns 0 on success.
int pap_disclosure_entry_set_no_retention(struct PapDisclosureEntry *e, int no_retention);

// Free a PapDisclosureEntry. Passing NULL is a no-op.
// # Safety
// `e` must be a pointer previously returned by `pap_disclosure_entry_new`.
void pap_disclosure_entry_free(struct PapDisclosureEntry *e);

// Create an empty disclosure set (disclose nothing).
struct PapDisclosureSet *pap_disclosure_set_empty(void);

// Build a DisclosureSet from an array of PapDisclosureEntry pointers (cloned).
// `entries` may be NULL when `count` is 0.
// # Safety
// `entries` must be a valid array of `count` non-null pointers.
struct PapDisclosureSet *pap_disclosure_set_new(const struct PapDisclosureEntry *const *entries,
                                                uintptr_t count);

// Free a PapDisclosureSet. Passing NULL is a no-op.
// # Safety
// `ds` must be a pointer previously returned by a `pap_disclosure_set_*` function.
void pap_disclosure_set_free(struct PapDisclosureSet *ds);

// Issue a root mandate directly by the principal.
// `ttl_rfc3339` is an RFC 3339 timestamp, e.g. `"2026-03-22T12:00:00Z"`.
// Returns NULL on parse error or null pointer argument.
struct PapMandate *pap_mandate_issue_root(const char *principal_did,
                                          const char *agent_did,
                                          const struct PapScope *scope,
                                          const struct PapDisclosureSet *disclosure_set,
                                          const char *ttl_rfc3339);

// Delegate a child mandate from an existing parent mandate.
// Enforces: child scope ⊆ parent scope; child TTL ≤ parent TTL.
// Returns NULL on scope/TTL violation.
struct PapMandate *pap_mandate_delegate(const struct PapMandate *parent,
                                        const char *agent_did,
                                        const struct PapScope *scope,
                                        const struct PapDisclosureSet *disclosure_set,
                                        const char *ttl_rfc3339);

// Free a PapMandate. Passing NULL is a no-op.
// # Safety
// `m` must be a pointer previously returned by a `pap_mandate_*` function.
void pap_mandate_free(struct PapMandate *m);

// Sign the mandate with the issuer's keypair. Must be called before use.
// Returns 0 on success, -1 on null pointer.
// # Safety
// Both `m` and `kp` must be valid non-null handles.
int pap_mandate_sign(struct PapMandate *m, const struct PapPrincipalKeypair *kp);

// Verify the mandate's Ed25519 signature against `pubkey_bytes` (32 bytes).
// Returns 0 on success, -1 on failure.
// # Safety
// `pubkey_bytes` must point to exactly 32 bytes.
int pap_mandate_verify(const struct PapMandate *m,
                       const uint8_t *pubkey_bytes,
                       uintptr_t pubkey_len);

// Serialize the mandate to a JSON C string. Caller frees with `pap_string_free`.
char *pap_mandate_to_json(const struct PapMandate *m);

// Deserialize a mandate from a JSON C string. Caller frees with `pap_mandate_free`.
// NOTE: `decay_state` in the JSON is *not* covered by the signature.
// Always call `pap_mandate_sync_decay_state` after deserialization to get the
// correct time-computed decay state.
struct PapMandate *pap_mandate_from_json(const char *json);

// Returns the mandate's SHA-256 hash (base64url) as a C string.
// Caller frees with `pap_string_free`.
// The hash covers all signed fields but excludes `decay_state` and `signature`.
char *pap_mandate_hash(const struct PapMandate *m);

// Returns the current decay state as an integer constant.
// See `PAP_DECAY_*` constants. Returns -1 on null input.
int pap_mandate_decay_state(const struct PapMandate *m);

// Compute the time-based decay state without mutating the mandate.
// `decay_window_secs` is the number of seconds before TTL at which the
// mandate enters Degraded state (e.g. 3600 for a 1-hour warning).
//
// IMPORTANT: This is a pure computation. The mandate's stored `decay_state`
// is NOT updated. Call `pap_mandate_sync_decay_state` to apply the result.
//
// Returns the computed state integer, or -1 on null input.
int pap_mandate_compute_decay_state(const struct PapMandate *m, int64_t decay_window_secs);

// Explicitly transition the mandate's decay state.
// Valid transitions (per spec): Active→Degraded, Degraded→ReadOnly,
// ReadOnly→Suspended, Degraded→Active (renewal), ReadOnly→Active (renewal).
// Suspended is terminal — no further transitions are allowed.
//
// NOTE: If the TTL has expired before a polling cycle ran, calling this with
// ReadOnly on an Active mandate will fail (Active→ReadOnly is not a valid
// single-step transition). Use `pap_mandate_sync_decay_state` instead, which
// handles multi-step transitions automatically.
//
// Returns 0 on success, -1 on invalid transition.
int pap_mandate_transition_decay(struct PapMandate *m, int next_state);

// Synchronize the mandate's stored decay state to the time-computed value.
//
// This is the safe high-level alternative to calling `compute_decay_state`
// and `transition_decay` manually. It handles the self-transition guard:
// calling `transition_decay` with the current state is rejected by the spec
// state machine, so this function is a no-op when the computed state equals
// the current state.
//
// The one-step guarantee (Active→Degraded→ReadOnly→Suspended, never
// skipping an intermediate) is now enforced by `compute_decay_state` itself
// per spec §5.7.1 — no special handling is needed here.
//
// Returns 0 on success (including no-op), -1 on error.
int pap_mandate_sync_decay_state(struct PapMandate *m, int64_t decay_window_secs);

// Returns 1 if `now > ttl`, 0 otherwise. Returns -1 on null input.
int pap_mandate_is_expired(const struct PapMandate *m);

// Returns the principal DID. Caller frees with `pap_string_free`.
char *pap_mandate_principal_did(const struct PapMandate *m);

// Returns the agent DID. Caller frees with `pap_string_free`.
char *pap_mandate_agent_did(const struct PapMandate *m);

// Returns the issuer DID. Caller frees with `pap_string_free`.
char *pap_mandate_issuer_did(const struct PapMandate *m);

// Returns the TTL as an RFC 3339 string. Caller frees with `pap_string_free`.
char *pap_mandate_ttl(const struct PapMandate *m);

// Mint a new capability token.
// `expires_at_rfc3339` is an RFC 3339 expiry timestamp.
struct PapCapabilityToken *pap_token_mint(const char *target_did,
                                          const char *action,
                                          const char *issuer_did,
                                          const char *expires_at_rfc3339);

// Free a PapCapabilityToken. Passing NULL is a no-op.
// # Safety
// `t` must be a pointer previously returned by a `pap_token_*` function.
void pap_token_free(struct PapCapabilityToken *t);

// Sign the token with the issuer's keypair. Returns 0 on success.
// # Safety
// Both `t` and `kp` must be valid non-null handles.
int pap_token_sign(struct PapCapabilityToken *t, const struct PapPrincipalKeypair *kp);

// Serialize the token to a JSON C string. Caller frees with `pap_string_free`.
char *pap_token_to_json(const struct PapCapabilityToken *t);

// Deserialize a capability token from JSON. Caller frees with `pap_token_free`.
struct PapCapabilityToken *pap_token_from_json(const char *json);

// Initiate a new session from a capability token.
// `issuer_pubkey` must point to exactly 32 bytes (Ed25519 public key of the
// token issuer, used to verify the token signature).
// Returns NULL on verification failure.
// # Safety
// `issuer_pubkey` must point to at least 32 bytes.
struct PapSession *pap_session_initiate(const struct PapCapabilityToken *token,
                                        const char *receiver_did,
                                        const uint8_t *issuer_pubkey,
                                        uintptr_t pubkey_len);

// Free a PapSession. Passing NULL is a no-op.
// # Safety
// `s` must be a pointer previously returned by `pap_session_initiate`.
void pap_session_free(struct PapSession *s);

// Open the session by exchanging ephemeral session DIDs.
// Both DIDs are typically `did:key` identifiers from freshly-generated
// `PapSessionKeypair`s. Returns 0 on success.
int pap_session_open(struct PapSession *s,
                     const char *initiator_session_did,
                     const char *receiver_session_did);

// Transition the session to Executed state. Returns 0 on success.
int pap_session_execute(struct PapSession *s);

// Close the session and discard ephemeral state. Returns 0 on success.
int pap_session_close(struct PapSession *s);

// Returns the session state as an integer.
// See `PAP_SESSION_*` constants. Returns -1 on null input.
int pap_session_state(const struct PapSession *s);

// Returns the session UUID as a C string. Caller frees with `pap_string_free`.
char *pap_session_id(const struct PapSession *s);

// Create a receipt from an executed session.
// `init_disc` / `recv_disc` are arrays of C strings describing property refs.
// # Safety
// All pointer arrays must be valid for their given counts.
struct PapReceipt *pap_receipt_from_session(const struct PapSession *session,
                                            const char *const *init_disc,
                                            uintptr_t init_disc_count,
                                            const char *const *recv_disc,
                                            uintptr_t recv_disc_count,
                                            const char *executed,
                                            const char *returned);

// Free a PapReceipt. Passing NULL is a no-op.
// # Safety
// `r` must be a pointer previously returned by a `pap_receipt_*` function.
void pap_receipt_free(struct PapReceipt *r);

// Co-sign the receipt with a keypair. Returns 0 on success.
// # Safety
// Both `r` and `kp` must be valid non-null handles.
int pap_receipt_co_sign(struct PapReceipt *r, const struct PapPrincipalKeypair *kp);

// Verify a specific co-signature on the receipt.
// `pubkey_bytes` must point to exactly 32 bytes.
// Returns 0 on success, -1 on failure.
// # Safety
// `pubkey_bytes` must point to at least 32 bytes.
int pap_receipt_verify_signature(const struct PapReceipt *r,
                                 uintptr_t index,
                                 const uint8_t *pubkey_bytes,
                                 uintptr_t pubkey_len);

// Verify both co-signatures on the receipt.
// Both key buffers must be exactly 32 bytes.
// Returns 0 on success, -1 on failure.
// # Safety
// Both pubkey pointers must point to at least 32 bytes.
int pap_receipt_verify_both(const struct PapReceipt *r,
                            const uint8_t *init_pubkey,
                            uintptr_t init_len,
                            const uint8_t *recv_pubkey,
                            uintptr_t recv_len);

// Serialize the receipt to a JSON C string. Caller frees with `pap_string_free`.
char *pap_receipt_to_json(const struct PapReceipt *r);

// Deserialize a receipt from a JSON C string. Caller frees with `pap_receipt_free`.
struct PapReceipt *pap_receipt_from_json(const char *json);

// Returns the receipt's session ID. Caller frees with `pap_string_free`.
char *pap_receipt_session_id(const struct PapReceipt *r);

// Returns the receipt's action. Caller frees with `pap_string_free`.
char *pap_receipt_action(const struct PapReceipt *r);

// Returns the number of co-signatures on the receipt.
// Returns -1 on null input.
int pap_receipt_signature_count(const struct PapReceipt *r);

// Create a new agent advertisement.
// All string arrays are borrowed C strings.
// # Safety
// All pointer arrays must be valid for their given counts.
struct PapAdvertisement *pap_advertisement_new(const char *name,
                                               const char *provider_name,
                                               const char *operator_did,
                                               const char *const *capabilities,
                                               uintptr_t cap_count,
                                               const char *const *object_types,
                                               uintptr_t obj_count,
                                               const char *const *requires_disclosure,
                                               uintptr_t disc_count,
                                               const char *const *returns,
                                               uintptr_t ret_count);

// Free a PapAdvertisement. Passing NULL is a no-op.
// # Safety
// `a` must be a pointer previously returned by a `pap_advertisement_*` function.
void pap_advertisement_free(struct PapAdvertisement *a);

// Sign the advertisement with the operator's keypair. Returns 0 on success.
// # Safety
// Both `a` and `kp` must be valid non-null handles.
int pap_advertisement_sign(struct PapAdvertisement *a, const struct PapPrincipalKeypair *kp);

// Verify the advertisement's signature. Returns 0 on success, -1 on failure.
// `pubkey_bytes` must point to exactly 32 bytes.
// # Safety
// `pubkey_bytes` must point to at least 32 bytes.
int pap_advertisement_verify(const struct PapAdvertisement *a,
                             const uint8_t *pubkey_bytes,
                             uintptr_t pubkey_len);

// Returns 1 if the advertisement supports `action`, 0 otherwise.
int pap_advertisement_supports_action(const struct PapAdvertisement *a, const char *action);

// Serialize the advertisement to a JSON C string. Caller frees with `pap_string_free`.
char *pap_advertisement_to_json(const struct PapAdvertisement *a);

// Deserialize an advertisement from JSON. Caller frees with `pap_advertisement_free`.
struct PapAdvertisement *pap_advertisement_from_json(const char *json);

// Returns the advertisement name. Caller frees with `pap_string_free`.
char *pap_advertisement_name(const struct PapAdvertisement *a);

// Create an empty marketplace registry.
struct PapMarketplaceRegistry *pap_registry_new(void);

// Free a PapMarketplaceRegistry. Passing NULL is a no-op.
// # Safety
// `r` must be a pointer previously returned by `pap_registry_new`.
void pap_registry_free(struct PapMarketplaceRegistry *r);

// Register an advertisement with the registry. The advertisement is cloned.
// Returns 0 on success, -1 if the advertisement is unsigned.
// # Safety
// Both `r` and `a` must be valid non-null handles.
int pap_registry_register(struct PapMarketplaceRegistry *r, const struct PapAdvertisement *a);

// Query for advertisements matching `action`. Returns results as a JSON array
// C string. Caller frees with `pap_string_free`.
// Returns NULL on error.
char *pap_registry_query_by_action(const struct PapMarketplaceRegistry *r, const char *action);

// Returns the number of advertisements in the registry. -1 on null input.
int pap_registry_len(const struct PapMarketplaceRegistry *r);

// Create M-of-N Shamir shards from a 32-byte Ed25519 seed.
//
// `seed_bytes` must point to exactly 32 bytes.
// `threshold` is M (minimum shards required to reconstruct).
// `total_shares` is N (number of shards to produce).
//
// Returns an opaque shard-set handle on success, NULL on error.
// The caller owns the set and must free it with `pap_recovery_shard_set_free`.
//
// # Safety
// `seed_bytes` must be valid for 32 bytes.
struct PapRecoveryShardSet *pap_recovery_create_shards(const uint8_t *seed_bytes,
                                                       uint8_t threshold,
                                                       uint8_t total_shares);

// Free a shard set (and all shards within it). Passing NULL is a no-op.
// # Safety
// `set` must be a pointer previously returned by `pap_recovery_create_shards`, or NULL.
void pap_recovery_shard_set_free(struct PapRecoveryShardSet *set);

// Returns the number of shards in the set, or -1 on null input.
int pap_recovery_shard_count(const struct PapRecoveryShardSet *set);

// Borrow the shard at position `index` (0-based) from a shard set.
//
// The returned pointer is **borrowed** — do NOT free it individually; free the entire
// set with `pap_recovery_shard_set_free`.  The pointer is valid until the set is freed.
//
// Returns NULL if `index` is out of range or `set` is NULL.
const struct PapRecoveryShard *pap_recovery_shard_get(const struct PapRecoveryShardSet *set,
                                                      int index);

// Serialize the shard manifest (public commitment document) to JSON.
//
// Returns a heap-allocated C string. Caller must free with `pap_string_free`.
// Returns NULL on error.
char *pap_recovery_shard_set_manifest_json(const struct PapRecoveryShardSet *set);

// Reconstruct a 32-byte seed from M or more Shamir shards.
//
// `shards` is an array of `shard_count` pointers to `PapRecoveryShard`.
// These may be borrowed from a `PapRecoveryShardSet` or owned handles returned
// by `pap_recovery_shard_from_json`.
//
// `seed_out` must point to a caller-allocated 32-byte buffer.
//
// Returns 0 on success, -1 on error. On error, `seed_out` is zeroed.
//
// # Safety
// `shards` must be a valid array of `shard_count` non-null `PapRecoveryShard` pointers.
// `seed_out` must point to at least 32 bytes.
int pap_recovery_reconstruct(const struct PapRecoveryShard *const *shards,
                             int shard_count,
                             uint8_t *seed_out);

// Serialize a single shard to a JSON string for distribution to a trustee.
//
// Returns a heap-allocated C string. Caller must free with `pap_string_free`.
// Returns NULL on error.
//
// # Safety
// `shard` must be a valid pointer (borrowed from a shard set or owned from
// `pap_recovery_shard_from_json`).
char *pap_recovery_shard_to_json(const struct PapRecoveryShard *shard);

// Deserialize a shard from a JSON string received from a trustee.
//
// Returns an owned `PapRecoveryShard` handle. The caller must free it with
// `pap_recovery_shard_free`. Returns NULL on parse error.
struct PapRecoveryShard *pap_recovery_shard_from_json(const char *json);

// Free a standalone shard handle (one returned by `pap_recovery_shard_from_json`).
//
// Do NOT use this on shards borrowed from a `PapRecoveryShardSet` — free the set instead.
// Passing NULL is a no-op.
//
// # Safety
// `shard` must be a pointer previously returned by `pap_recovery_shard_from_json`, or NULL.
void pap_recovery_shard_free(struct PapRecoveryShard *shard);

// Create a marketplace client wrapping a local registry.
//
// `registry_url` is stored for forward compatibility with networked
// federation but has no runtime effect in this PoC.
// Returns NULL on null or invalid UTF-8 input.
struct PapMarketplaceClient *pap_marketplace_client_new(const char *registry_url);

// Free a PapMarketplaceClient. Passing NULL is a no-op.
// # Safety
// `client` must be a pointer previously returned by `pap_marketplace_client_new`.
void pap_marketplace_client_free(struct PapMarketplaceClient *client);

// Register an advertisement with the client's internal registry.
// The advertisement is cloned. Returns 0 on success, -1 if unsigned.
// # Safety
// Both `client` and `a` must be valid non-null handles.
int pap_marketplace_client_register(struct PapMarketplaceClient *client,
                                    const struct PapAdvertisement *a);

// Query the client's registry for agents matching a capability.
//
// `capability_json` is a JSON object with:
//   - `"action"` (required): Schema.org action type string
//   - `"available_properties"` (optional): JSON array of property strings
//
// If `available_properties` is present, uses disclosure-filtered matching;
// otherwise matches by action alone.
//
// Returns a `PapAgentList` handle that the caller must free with
// `pap_agent_list_free`. Returns NULL on error.
struct PapAgentList *pap_marketplace_query(const struct PapMarketplaceClient *client,
                                           const char *capability_json);

// Returns the number of agents in the result list. Returns 0 on null input.
uintptr_t pap_agent_list_len(const struct PapAgentList *list);

// Returns the DID of the agent at `index` as a borrowed C string.
//
// The returned pointer is valid until `pap_agent_list_free` is called.
// Do NOT free this pointer with `pap_string_free`.
// Returns NULL if `list` is null or `index` is out of bounds.
const char *pap_agent_list_get_did(const struct PapAgentList *list, uintptr_t index);

// Returns the name of the agent at `index` as a borrowed C string.
//
// The returned pointer is valid until `pap_agent_list_free` is called.
// Do NOT free this pointer with `pap_string_free`.
// Returns NULL if `list` is null or `index` is out of bounds.
const char *pap_agent_list_get_name(const struct PapAgentList *list, uintptr_t index);

// Free a PapAgentList and all its owned strings. Passing NULL is a no-op.
//
// After this call, all pointers previously returned by
// `pap_agent_list_get_did` and `pap_agent_list_get_name` for this
// list are invalidated.
// # Safety
// `list` must be a pointer previously returned by `pap_marketplace_query`.
void pap_agent_list_free(struct PapAgentList *list);

// Generate a new ecash mint keypair.
//
// `key_bits` MUST be ≥ 2048 for production; 1024 is acceptable for tests.
// Returns NULL on failure; call `pap_last_error_message()` for details.
// Caller must free with `pap_ecash_mint_keypair_free`.
struct PapEcashMintKeypair *pap_ecash_mint_keypair_generate(unsigned int key_bits);

// Free a keypair returned by `pap_ecash_mint_keypair_generate`.
// # Safety
// `kp` must be a pointer previously returned by that function, or NULL.
void pap_ecash_mint_keypair_free(struct PapEcashMintKeypair *kp);

// Serialize the mint public key as a PKCS#1 PEM string.
//
// Returns NULL on failure. Caller must free the returned string with
// `pap_string_free`.
char *pap_ecash_mint_keypair_public_pem(const struct PapEcashMintKeypair *kp);

// **Client:** Blind a serial number against the mint's public key.
//
// `mint_public_pem` — PKCS#1 PEM string from `pap_ecash_mint_keypair_public_pem`.
// `serial` — pointer to `serial_len` bytes (typically 32).
//
// Returns an opaque handle or NULL on failure.
// Caller must free with `pap_ecash_blind_token_free`.
// Only `pap_ecash_blind_message_bytes` should be sent to the mint.
struct PapEcashBlindToken *pap_ecash_blind(const char *mint_public_pem,
                                           const uint8_t *serial,
                                           uintptr_t serial_len);

// Return the blinded-message bytes from a blind token — the only bytes to
// transmit to the mint.
//
// `out_len` — written with the byte count (may be NULL if unneeded).
// Returns a heap-allocated byte array. Free with `pap_bytes_free(ptr, len)`.
// Returns NULL on failure.
uint8_t *pap_ecash_blind_message_bytes(const struct PapEcashBlindToken *bt, uintptr_t *out_len);

// Free a blind token returned by `pap_ecash_blind`.
// # Safety
// `bt` must be a pointer previously returned by that function, or NULL.
void pap_ecash_blind_token_free(struct PapEcashBlindToken *bt);

// **Mint:** Sign a blinded message and return the raw blind-signature bytes.
//
// `blinded_msg` — bytes from `pap_ecash_blind_message_bytes` on the client.
// `out_sig_len` — if non-NULL, written with the byte count of the returned array.
//
// Returns a heap-allocated byte array. Free with `pap_bytes_free(ptr, len)`.
// Returns NULL on failure.
uint8_t *pap_ecash_mint_sign(const struct PapEcashMintKeypair *kp,
                             const uint8_t *blinded_msg,
                             uintptr_t blinded_len,
                             uintptr_t *out_sig_len);

// **Client:** Unblind the mint's signature to produce a redeemable token.
//
// `mint_public_pem` — same PKCS#1 PEM used during blinding.
// `bt` — the blind token from `pap_ecash_blind` (still held by the client).
// `blind_sig` / `blind_sig_len` — bytes returned by the mint.
//
// Returns an opaque token handle or NULL on failure.
// Caller must free with `pap_ecash_token_free`.
struct PapEcashToken *pap_ecash_unblind(const char *mint_public_pem,
                                        const struct PapEcashBlindToken *bt,
                                        const uint8_t *blind_sig,
                                        uintptr_t blind_sig_len);

// Return the base64url-no-pad SHA-256 payment-proof commitment for a token.
//
// Caller must free the returned string with `pap_string_free`.
// Returns NULL on failure.
char *pap_ecash_token_payment_proof_commitment(const struct PapEcashToken *token);

// Return the 32-byte serial from an ecash token.
//
// `out_len` — if non-NULL, written with the byte count (always 32).
// Returns a heap-allocated byte array. Free with `pap_bytes_free(ptr, len)`.
// Returns NULL on failure.
uint8_t *pap_ecash_token_serial(const struct PapEcashToken *token, uintptr_t *out_len);

// Return the unblinded signature bytes from an ecash token.
//
// `out_len` — if non-NULL, written with the byte count.
// Returns a heap-allocated byte array. Free with `pap_bytes_free(ptr, len)`.
// Returns NULL on failure.
uint8_t *pap_ecash_token_signature(const struct PapEcashToken *token, uintptr_t *out_len);

// Free a token returned by `pap_ecash_unblind`.
// # Safety
// `token` must be a pointer previously returned by that function, or NULL.
void pap_ecash_token_free(struct PapEcashToken *token);

// **Payee:** Verify a token without recording it in the spent registry.
//
// Returns `0` if the signature is valid, `-1` otherwise.
// Does not protect against double-spend — use `pap_ecash_redeem` for that.
int pap_ecash_verify(const char *mint_public_pem,
                     const uint8_t *serial,
                     uintptr_t serial_len,
                     const uint8_t *sig,
                     uintptr_t sig_len);

// Create a new empty double-spend registry.
// Caller must free with `pap_ecash_spent_registry_free`.
struct PapEcashSpentRegistry *pap_ecash_spent_registry_new(void);

// Free a registry returned by `pap_ecash_spent_registry_new`.
// # Safety
// `r` must be a pointer previously returned by that function, or NULL.
void pap_ecash_spent_registry_free(struct PapEcashSpentRegistry *r);

// **Payee:** Verify a token and atomically record its serial as spent.
//
// Returns `0` on success (first redemption of a valid token).
// Returns `-1` with a descriptive last-error on double-spend or invalid sig.
int pap_ecash_redeem(const char *mint_public_pem,
                     const uint8_t *serial,
                     uintptr_t serial_len,
                     const uint8_t *sig,
                     uintptr_t sig_len,
                     struct PapEcashSpentRegistry *registry);

// Free a byte array previously returned by `pap_ecash_blind_message_bytes`
// or `pap_ecash_mint_sign`.
//
// # Safety
// `ptr` must be a pointer previously returned by one of those functions (or
// NULL). `len` must be the exact length reported by that call.
void pap_bytes_free(uint8_t *ptr, uintptr_t len);

#endif  /* PAP_H */
