//! Persistent Ed25519 principal keypair storage.
//!
//! The principal's root keypair is the root of trust for all PAP mandates.
//! This module persists it to `{app_data_dir}/principal.key` as a 32-byte raw
//! Ed25519 seed with Unix file permissions 0600 (owner-readable only).
//!
//! # Security properties
//! - Seed bytes are stored in a [`zeroize::Zeroizing`] wrapper and zeroized on drop.
//! - File is created with mode 0600 before any data is written (on Unix).
//! - On first launch a new keypair is generated with [`rand::rngs::OsRng`].
//! - On subsequent launches the existing seed is read and validated.

use std::io;
use std::path::{Path, PathBuf};

use ed25519_dalek::SigningKey;
use pap_did::PrincipalKeypair;
use rand::rngs::OsRng;
use zeroize::Zeroizing;

/// File name used within the app data directory.
const KEY_FILE_NAME: &str = "principal.key";

/// Unix file mode for the key file: owner read+write only.
#[cfg(unix)]
const KEY_FILE_MODE: u32 = 0o600;

/// Manages the persistent Ed25519 principal keypair.
///
/// The key material is stored as a 32-byte raw seed in
/// `{app_data_dir}/principal.key` with permissions 0600.
///
/// The in-memory seed is held in a [`Zeroizing`] wrapper and is securely
/// erased when this struct is dropped.
pub struct KeypairStore {
    /// Path to the persisted key file.
    key_path: PathBuf,
    /// Zeroized 32-byte Ed25519 seed.
    seed: Zeroizing<[u8; 32]>,
}

impl KeypairStore {
    /// Open (or create) the keypair store backed by `app_data_dir`.
    ///
    /// - If `principal.key` does not exist, generates a fresh Ed25519 keypair
    ///   using [`OsRng`], writes the 32-byte seed to the file with mode 0600,
    ///   and returns the new store.
    /// - If the file exists, reads and validates the seed (must be exactly
    ///   32 bytes and form a valid signing key) and returns the existing store.
    ///
    /// # Errors
    /// Returns [`io::Error`] if the file cannot be read, written, or if the
    /// stored seed is invalid (wrong length or malformed key bytes).
    pub fn open(app_data_dir: &Path) -> io::Result<Self> {
        let key_path = app_data_dir.join(KEY_FILE_NAME);

        let seed = if key_path.exists() {
            Self::load_seed(&key_path)?
        } else {
            Self::generate_and_persist(&key_path)?
        };

        Ok(Self { key_path, seed })
    }

    /// Returns the `did:key` DID derived from the persisted keypair.
    ///
    /// # Panics
    /// This method panics if the stored seed cannot be used to reconstruct a
    /// valid keypair, which should never happen given that the seed was either
    /// generated by `ed25519_dalek` or validated on load.
    pub fn principal_did(&self) -> String {
        PrincipalKeypair::from_bytes(&self.seed)
            .expect("keypair_store: stored seed must form a valid keypair")
            .did()
    }

    /// Returns a reference to the underlying [`SigningKey`].
    ///
    /// The returned key can be used directly for signing PAP mandates and
    /// agent advertisements.
    pub fn signing_key(&self) -> SigningKey {
        SigningKey::from_bytes(&self.seed)
    }

    /// Returns the path to the persisted key file.
    pub fn key_path(&self) -> &Path {
        &self.key_path
    }

    // ── Private helpers ────────────────────────────────────────────────────

    /// Load and validate a seed from an existing key file.
    fn load_seed(key_path: &Path) -> io::Result<Zeroizing<[u8; 32]>> {
        let bytes = std::fs::read(key_path)?;
        if bytes.len() != 32 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "principal.key: expected 32 bytes, got {} — key file may be corrupt",
                    bytes.len()
                ),
            ));
        }

        let mut seed = [0u8; 32];
        seed.copy_from_slice(&bytes);

        // Validate: ensure the bytes form a syntactically valid signing key.
        // ed25519-dalek accepts any 32-byte value as a signing key seed; we
        // construct the key to confirm it round-trips without panicking.
        let _signing_key = SigningKey::from_bytes(&seed);

        Ok(Zeroizing::new(seed))
    }

    /// Generate a new Ed25519 keypair, write the seed to disk with mode 0600,
    /// and return the seed.
    fn generate_and_persist(key_path: &Path) -> io::Result<Zeroizing<[u8; 32]>> {
        let signing_key = SigningKey::generate(&mut OsRng);
        let seed = signing_key.to_bytes();

        Self::write_key_file(key_path, &seed)?;

        Ok(Zeroizing::new(seed))
    }

    /// Atomically write `seed` bytes to `key_path` with mode 0600.
    ///
    /// On Unix the file is created with `O_CREAT | O_WRONLY | O_TRUNC` and the
    /// mode is set to 0600 before any data is written. On other platforms the
    /// file is created and then the mode is updated post-write.
    fn write_key_file(key_path: &Path, seed: &[u8; 32]) -> io::Result<()> {
        #[cfg(unix)]
        {
            use std::fs::OpenOptions;
            use std::io::Write;
            use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

            let mut file = OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .mode(KEY_FILE_MODE)
                .open(key_path)?;

            file.write_all(seed)?;
            file.sync_all()?;

            // Explicitly set permissions in case umask overrode the mode.
            let perms = std::fs::Permissions::from_mode(KEY_FILE_MODE);
            std::fs::set_permissions(key_path, perms)?;
        }

        #[cfg(not(unix))]
        {
            use std::io::Write;

            let mut file = std::fs::File::create(key_path)?;
            file.write_all(seed)?;
            file.sync_all()?;
        }

        Ok(())
    }
}

// KeypairStore deliberately does not implement Clone — the seed must not be
// copied inadvertently. The Zeroizing wrapper ensures the seed is erased when
// the struct is dropped.

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn temp_dir() -> TempDir {
        tempfile::tempdir().expect("failed to create temp dir")
    }

    #[test]
    fn creates_key_file_on_first_open() {
        let dir = temp_dir();
        let store = KeypairStore::open(dir.path()).expect("should create store");

        let key_path = dir.path().join(KEY_FILE_NAME);
        assert!(key_path.exists(), "principal.key should exist after open");

        // Seed must be 32 bytes
        let bytes = std::fs::read(&key_path).unwrap();
        assert_eq!(bytes.len(), 32, "key file must be exactly 32 bytes");

        // DID should start with did:key:
        assert!(
            store.principal_did().starts_with("did:key:"),
            "principal_did() must return a did:key DID"
        );
    }

    #[test]
    fn persists_and_reloads_same_keypair() {
        let dir = temp_dir();

        let did1 = {
            let store = KeypairStore::open(dir.path()).expect("first open");
            store.principal_did()
        };

        let did2 = {
            let store = KeypairStore::open(dir.path()).expect("second open");
            store.principal_did()
        };

        assert_eq!(did1, did2, "DID must be stable across restarts");
    }

    #[test]
    #[cfg(unix)]
    fn key_file_has_mode_0600() {
        use std::os::unix::fs::PermissionsExt;
        let dir = temp_dir();
        KeypairStore::open(dir.path()).expect("should create store");

        let key_path = dir.path().join(KEY_FILE_NAME);
        let meta = std::fs::metadata(&key_path).unwrap();
        let mode = meta.permissions().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "principal.key must have mode 0600, got {mode:o}"
        );
    }

    #[test]
    fn rejects_corrupt_key_file_wrong_length() {
        let dir = temp_dir();
        let key_path = dir.path().join(KEY_FILE_NAME);

        // Write 31 bytes instead of 32
        std::fs::write(&key_path, vec![0u8; 31]).unwrap();

        let result = KeypairStore::open(dir.path());
        assert!(result.is_err(), "should reject 31-byte key file");
        let err = result.err().unwrap();
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
    }

    #[test]
    fn signing_key_matches_persisted_seed() {
        let dir = temp_dir();
        let store = KeypairStore::open(dir.path()).expect("should create store");

        let seed_bytes = std::fs::read(dir.path().join(KEY_FILE_NAME)).unwrap();
        let mut seed = [0u8; 32];
        seed.copy_from_slice(&seed_bytes);

        let expected = SigningKey::from_bytes(&seed);
        let got = store.signing_key();
        assert_eq!(
            expected.to_bytes(),
            got.to_bytes(),
            "signing_key() must match persisted seed"
        );
    }

    #[test]
    fn seed_is_zeroized_on_drop() {
        // Validate the Zeroizing wrapper compiles and executes correctly.
        let seed: Zeroizing<[u8; 32]> = Zeroizing::new([0xABu8; 32]);
        drop(seed);
        // Zeroize executes on drop — verifiable via MSAN/valgrind in CI.
    }
}
