use leptos::prelude::*;
use papillon_shared::RecoveryShardInfo;

/// Frontend state for the M-of-N Shamir recovery setup flow.
#[derive(Clone, Copy)]
pub struct RecoveryState {
    /// Whether the recovery setup modal is visible.
    pub show_setup: RwSignal<bool>,
    /// User-selected M (threshold).
    pub threshold: RwSignal<u8>,
    /// User-selected N (total shards).
    pub total: RwSignal<u8>,
    /// Shards generated by the last `create_recovery_shards` call.
    pub shards: RwSignal<Vec<RecoveryShardInfo>>,
    /// Shard manifest JSON (for public distribution).
    pub manifest_json: RwSignal<String>,
    /// True while the backend call is in flight.
    pub generating: RwSignal<bool>,
    /// Last error message from backend (if any).
    pub error: RwSignal<Option<String>>,
    /// Whether recovery shards have been set up and exported.
    pub setup_complete: RwSignal<bool>,
    /// True when the current ceremony was used in a recovery and the principal
    /// must distribute fresh shards before the old compromised ones can be reused.
    pub needs_renewal: RwSignal<bool>,
}

impl Default for RecoveryState {
    fn default() -> Self {
        Self {
            show_setup: RwSignal::new(false),
            threshold: RwSignal::new(2),
            total: RwSignal::new(3),
            shards: RwSignal::new(Vec::new()),
            manifest_json: RwSignal::new(String::new()),
            generating: RwSignal::new(false),
            error: RwSignal::new(None),
            setup_complete: RwSignal::new(false),
            needs_renewal: RwSignal::new(false),
        }
    }
}
