/**
 * 500-prompt coverage test suite for Papillon.
 *
 * 20 categories × 25 prompts each = 500 realistic user prompts.
 * Each category has:
 *   - 1 mock-keyword test (guaranteed typed block render)
 *   - 5 natural-language prompt tests (go through generic submit → canvas block)
 *
 * Run a specific category: npx playwright test --grep "movies"
 * Run all: npx playwright test tests/prompt-coverage.spec.ts
 */

import { test, expect } from "@playwright/test";
import { installTauriMock } from "./tauri-mock";
import { waitForApp, submitPrompt } from "./helpers";

test.beforeEach(async ({ page }) => {
  await installTauriMock(page);
});

// ── Category definitions ──────────────────────────────────────

const PROMPT_CATEGORIES = [
  {
    category: "movies",
    mockKeyword: "mock:movie",
    cssClass: ".typed-movie",
    contentSelector: ".typed-movie-title",
    contentMatch: "Inception",
    prompts: [
      "What movies are playing tonight?",
      "Find me a good action movie from the 90s",
      "Show me Christopher Nolan films",
      "Best sci-fi movies of all time",
      "Movies similar to The Matrix",
      "Find films directed by Denis Villeneuve",
      "Top rated horror movies on Rotten Tomatoes",
      "What won best picture last year?",
      "Comedy movies for family night",
      "Foreign language films with subtitles",
      "Movies starring Cate Blanchett",
      "Best animated movies for kids",
      "Films based on true stories",
      "Highest grossing movies ever made",
      "Independent films from Sundance 2024",
      "Movies about artificial intelligence",
      "Classic films from the golden age of Hollywood",
      "Best documentaries on Netflix",
      "Award winning short films",
      "Movies with the best soundtracks",
      "Noir detective films from the 1940s",
      "Best heist movies of all time",
      "Films that defined the 1980s",
      "Movies about space exploration",
      "Best movie sequels better than the original",
    ],
  },
  {
    category: "weather",
    mockKeyword: "mock:weather",
    cssClass: ".typed-weather",
    contentSelector: ".typed-weather-location",
    contentMatch: "San Francisco",
    prompts: [
      "What's the weather like today?",
      "Will it rain this weekend?",
      "Current temperature in New York",
      "5-day forecast for Chicago",
      "Is it going to snow tomorrow?",
      "Weather for my morning commute",
      "Best time to visit Hawaii weather-wise",
      "Humidity levels in Houston right now",
      "Wind speed at San Francisco airport",
      "UV index today in Miami",
      "Thunderstorm warnings near Dallas",
      "Pollen count for allergy season",
      "Weather conditions for hiking this weekend",
      "Sunrise and sunset times today",
      "Air quality index in Los Angeles",
      "Fog advisory for the Bay Bridge",
      "Heat index for outdoor sports today",
      "Historic rainfall totals this month",
      "Sea surface temperature in the Gulf",
      "Mountain snowpack levels in Colorado",
      "Weather along the Pacific Coast Highway",
      "Frost advisory for gardeners this week",
      "Wildfire risk conditions in California",
      "Tornado watch in Oklahoma",
      "Flash flood warnings in Arizona",
    ],
  },
  {
    category: "books",
    mockKeyword: "mock:book",
    cssClass: ".typed-book",
    contentSelector: ".typed-book-title",
    contentMatch: "Rust Programming Language",
    prompts: [
      "Find books by Ursula K. Le Guin",
      "Best programming books for beginners",
      "Science fiction novels published this year",
      "Books about climate change and environment",
      "Award winning novels from the Booker Prize",
      "History books about ancient Rome",
      "Self-help books for productivity",
      "Books similar to Harry Potter",
      "Graphic novels for adults",
      "Philosophy books for non-philosophers",
      "Best cookbooks for Italian cuisine",
      "Business books recommended by Bill Gates",
      "Classic literature everyone should read",
      "Books about the history of mathematics",
      "Thriller novels with female protagonists",
      "Books about machine learning for beginners",
      "Travel memoirs from around the world",
      "Books recommended by Barack Obama",
      "Short story collections by contemporary authors",
      "Books about the psychology of decision making",
      "Banned books and their significance",
      "Books about startups and entrepreneurship",
      "Poetry collections from the 20th century",
      "Children's books that become animated films",
      "Books about the history of the internet",
    ],
  },
  {
    category: "job postings",
    mockKeyword: "mock:jobposting",
    cssClass: ".typed-job-posting",
    contentSelector: ".typed-job-title",
    contentMatch: "Senior Rust Engineer",
    prompts: [
      "Remote software engineer jobs paying over $150k",
      "Entry level data science positions in Seattle",
      "Product manager roles at FAANG companies",
      "UX design jobs with flexible hours",
      "Cybersecurity analyst positions near me",
      "DevOps engineer jobs requiring Kubernetes",
      "Machine learning engineer openings at startups",
      "Technical writer positions fully remote",
      "iOS developer jobs in Austin Texas",
      "Backend Python developer roles in London",
      "Blockchain developer positions in New York",
      "QA automation engineer jobs with Playwright",
      "Cloud architect positions at Fortune 500",
      "Game developer jobs at indie studios",
      "Site reliability engineer openings",
      "Research scientist positions in AI labs",
      "Embedded systems engineer jobs in defense",
      "Frontend React developer roles in Berlin",
      "Security researcher positions at Google",
      "Rust systems programmer jobs",
      "Database administrator positions in healthcare",
      "Mobile developer jobs for React Native",
      "Full stack developer roles with equity",
      "Principal engineer positions at unicorn startups",
      "Open source developer roles with stipend",
    ],
  },
  {
    category: "people",
    mockKeyword: "mock:person",
    cssClass: ".typed-person",
    contentSelector: ".typed-person-name",
    contentMatch: "Grace Hopper",
    prompts: [
      "Who is Ada Lovelace?",
      "Tell me about Nikola Tesla",
      "Biography of Marie Curie",
      "Who invented the World Wide Web?",
      "Life and work of Alan Turing",
      "Who is Linus Torvalds?",
      "Tell me about Grace Hopper's contributions",
      "Biography of Richard Feynman",
      "Who is Guido van Rossum?",
      "Life story of Katherine Johnson",
      "Who founded Apple Computer?",
      "Tell me about Carl Sagan",
      "Biography of Claude Shannon",
      "Who is Vint Cerf?",
      "Tell me about Barbara Liskov",
      "Life of Douglas Engelbart",
      "Who invented email?",
      "Biography of John von Neumann",
      "Who is Radia Perlman?",
      "Tell me about Donald Knuth",
      "Biography of Frances Allen",
      "Who is Bjarne Stroustrup?",
      "Life of Margaret Hamilton",
      "Who created Unix?",
      "Tell me about Edsger Dijkstra",
    ],
  },
  {
    category: "events",
    mockKeyword: "mock:event",
    cssClass: ".typed-event",
    contentSelector: ".typed-event-name",
    contentMatch: "RustConf",
    prompts: [
      "Tech conferences in San Francisco this month",
      "Upcoming hackathons for students",
      "Music festivals in Europe this summer",
      "AI and machine learning summit schedule",
      "Open source contributor meetups",
      "JavaScript conferences to attend",
      "Women in tech networking events",
      "Startup pitch competitions near me",
      "Virtual conferences for remote developers",
      "Annual Rust programming conference",
      "DevOps days events worldwide",
      "Cybersecurity conferences in 2026",
      "Science fiction conventions this year",
      "Data science summit upcoming events",
      "Cloud computing expo schedule",
      "Blockchain developer conferences",
      "Gaming expos and fan conventions",
      "Academic computer science symposiums",
      "Product design conferences to attend",
      "Agile and Scrum certification workshops",
      "Quantum computing research conferences",
      "Creative coding and generative art events",
      "Open data hackathons and challenges",
      "Privacy and digital rights workshops",
      "Maker faire and hardware hacking events",
    ],
  },
  {
    category: "products",
    mockKeyword: "mock:product",
    cssClass: ".typed-product",
    contentSelector: ".typed-product-name",
    contentMatch: "Framework Laptop",
    prompts: [
      "Best laptops for software developers in 2026",
      "Mechanical keyboards under $150",
      "Ergonomic mice for long coding sessions",
      "Standing desks with programmable heights",
      "USB-C hubs with Thunderbolt 4 support",
      "4K monitors for photo editing",
      "NAS drives for home media server",
      "Noise cancelling headphones for office",
      "Smart home hubs that work offline",
      "Raspberry Pi alternatives for hobbyists",
      "3D printers for beginners under $500",
      "Electric bikes for city commuting",
      "Solar panels for small apartment balcony",
      "Portable power stations for camping",
      "Mesh WiFi systems for large homes",
      "Budget mirrorless cameras for YouTube",
      "Air purifiers for home office spaces",
      "Repairable and modular laptops",
      "Privacy-focused smartphones in 2026",
      "Linux-compatible hardware peripherals",
      "Portable SSDs for video production",
      "Smart thermostats that respect privacy",
      "Open source hardware projects",
      "Mechanical keyboards with QMK firmware",
      "Wireless earbuds with ANC under $100",
    ],
  },
  {
    category: "scholarly articles",
    mockKeyword: "mock:scholarlyarticle",
    cssClass: ".typed-scholarly-article",
    contentSelector: ".typed-paper-title",
    contentMatch: "Attention Is All You Need",
    prompts: [
      "Papers about transformer neural networks",
      "Research on federated learning privacy",
      "Academic papers on zero knowledge proofs",
      "Studies on large language model hallucination",
      "Peer reviewed research on climate models",
      "Academic literature on quantum cryptography",
      "Papers about WebAssembly performance",
      "Research on distributed systems consensus",
      "Studies on human-computer interaction design",
      "Papers about programming language type systems",
      "Academic research on social media algorithms",
      "Studies on urban heat islands",
      "Papers about CRISPR gene editing safety",
      "Research on renewable energy storage",
      "Academic papers on machine learning fairness",
      "Studies on misinformation spread online",
      "Papers about Rust memory safety proofs",
      "Research on autonomous vehicle ethics",
      "Academic studies on sleep deprivation effects",
      "Papers about decentralized identity systems",
      "Research on compiler optimization techniques",
      "Studies on antibiotic resistance mechanisms",
      "Papers about network traffic analysis",
      "Academic research on cognitive load theory",
      "Studies on open source software economics",
    ],
  },
  {
    category: "news articles",
    mockKeyword: "mock:newsarticle",
    cssClass: ".typed-news-article",
    contentSelector: ".typed-news-headline",
    contentMatch: "Rust Tops Developer Survey",
    prompts: [
      "Latest news about artificial intelligence regulation",
      "Technology headlines this morning",
      "News about open source software funding",
      "Updates on climate legislation in Congress",
      "Breaking news about cybersecurity breaches",
      "Latest developments in quantum computing",
      "News about electric vehicle adoption",
      "Updates on space exploration missions",
      "Tech industry layoffs and hiring trends",
      "News about privacy legislation in Europe",
      "Updates on decentralized web protocols",
      "Latest developments in programming languages",
      "News about cloud computing market share",
      "Updates on antitrust cases against big tech",
      "Cryptocurrency regulation news",
      "Open source AI model releases this week",
      "News about internet infrastructure changes",
      "Updates on developer tool ecosystems",
      "Latest security vulnerability disclosures",
      "News about chip shortages and supply chains",
      "Updates on WebAssembly adoption",
      "News about Rust in the Linux kernel",
      "Latest browser engine performance benchmarks",
      "Updates on digital identity standards",
      "News about edge computing deployments",
    ],
  },
  {
    category: "organizations",
    mockKeyword: "mock:organization",
    cssClass: ".typed-organization",
    contentSelector: ".typed-org-name",
    contentMatch: "Mozilla Foundation",
    prompts: [
      "Tell me about the Mozilla Foundation",
      "What is the Apache Software Foundation?",
      "Information about the Linux Foundation",
      "Who runs the Internet Archive?",
      "Tell me about Electronic Frontier Foundation",
      "What does the W3C do?",
      "Information about IETF standards body",
      "Who is the Open Source Initiative?",
      "Tell me about Creative Commons",
      "What is the Free Software Foundation?",
      "Information about the Rust Foundation",
      "Who runs ICANN and DNS governance?",
      "Tell me about the Internet Society",
      "What is the Digital Rights Foundation?",
      "Information about OpenStreetMap Foundation",
      "Who maintains the Python Software Foundation?",
      "Tell me about the Wikimedia Foundation",
      "What is the Open Web Foundation?",
      "Information about the Cloud Native Computing Foundation",
      "Who is behind the OpenAPI Initiative?",
      "Tell me about the OWASP security foundation",
      "What does the Unicode Consortium do?",
      "Information about the IEEE standards body",
      "Who runs the Let's Encrypt certificate authority?",
      "Tell me about the Internet Archive Wayback Machine",
    ],
  },
  {
    category: "geography",
    mockKeyword: "mock:geocoords",
    cssClass: ".typed-geocoords",
    contentSelector: ".typed-geo-name",
    contentMatch: "Eiffel Tower",
    prompts: [
      "Where is the Eiffel Tower located exactly?",
      "GPS coordinates for the Great Wall of China",
      "Location of the Statue of Liberty",
      "Where is Machu Picchu in Peru?",
      "Exact location of the Colosseum in Rome",
      "GPS coordinates for Mount Everest base camp",
      "Where is the Amazon River source?",
      "Location of the Northern Lights best viewing",
      "Coordinates for the Sahara Desert center",
      "Where is the International Space Station right now?",
      "Location of the deepest point in the ocean",
      "GPS coordinates for Stonehenge",
      "Where is the geographic center of the US?",
      "Location of the world's largest salt flat",
      "Coordinates for the Galapagos Islands",
      "Where is the Mariana Trench exactly?",
      "GPS location of the Chernobyl exclusion zone",
      "Where is the oldest continuously inhabited city?",
      "Coordinates for the South Pole research station",
      "Location of the world's highest waterfall",
      "Where is the largest coral reef system?",
      "GPS coordinates for Angkor Wat Cambodia",
      "Location of the Louvre museum in Paris",
      "Where is the tallest building in the world?",
      "Coordinates for the Amazon rainforest heart",
    ],
  },
  {
    category: "courses",
    mockKeyword: "mock:course",
    cssClass: ".typed-course",
    contentSelector: ".typed-course-name",
    contentMatch: "CS50",
    prompts: [
      "Best free online courses for learning Rust",
      "MIT OpenCourseWare computer science classes",
      "Coursera courses for machine learning beginners",
      "Online courses for data structures and algorithms",
      "Free Python programming courses for beginners",
      "Best courses for learning system design",
      "Online certifications for cloud architecture",
      "Web development bootcamps with job guarantees",
      "Courses for learning distributed systems",
      "Free university courses on compilers",
      "Online courses for cryptography fundamentals",
      "Best courses for React and TypeScript",
      "Machine learning courses by Andrew Ng",
      "Operating systems courses from Stanford",
      "Online courses for network security",
      "Courses for learning WebAssembly",
      "Database design and SQL courses online",
      "Courses for learning functional programming",
      "Online courses for Kubernetes and DevOps",
      "Competitive programming courses for beginners",
      "Courses for learning computer graphics",
      "Online machine learning math prerequisites",
      "Courses for learning Rust for embedded systems",
      "Free courses on formal verification methods",
      "Online courses for programming language theory",
    ],
  },
  {
    category: "music",
    mockKeyword: "mock:musicrecording",
    cssClass: ".typed-music-recording",
    contentSelector: ".typed-music-title",
    contentMatch: "Bohemian Rhapsody",
    prompts: [
      "What's the most streamed song of all time?",
      "Find songs similar to Bohemian Rhapsody",
      "Best jazz albums to listen to on a rainy day",
      "Top 10 classical pieces for studying",
      "Music for deep focus and concentration",
      "Best lo-fi hip hop playlists",
      "Songs that defined the 1970s rock era",
      "Find ambient music for meditation",
      "Best film scores by Hans Zimmer",
      "New wave music from the 1980s",
      "Songs with the most complex time signatures",
      "Best guitar solos in rock history",
      "Find traditional Irish folk music",
      "Electronic music pioneers from Berlin",
      "Best albums for a long road trip",
      "Songs that sample other famous tracks",
      "Latin jazz music recommendations",
      "Best soundtracks for working out",
      "Find music from the Baroque period",
      "Songs about technology and the future",
      "Best concept albums in progressive rock",
      "Find traditional Japanese music",
      "Music from the New Zealand indie scene",
      "Best hip hop albums from the 1990s",
      "Songs in unusual or odd time signatures",
    ],
  },
  {
    category: "defined terms",
    mockKeyword: "mock:definedterm",
    cssClass: ".typed-defined-term",
    contentSelector: ".typed-term-word",
    contentMatch: "monad",
    prompts: [
      "What is a monad in functional programming?",
      "Define Byzantine fault tolerance",
      "What does ACID mean in databases?",
      "Explain the CAP theorem",
      "What is a Merkle tree?",
      "Define zero-knowledge proof",
      "What is homomorphic encryption?",
      "Explain eventual consistency",
      "What is a content delivery network?",
      "Define dependency injection",
      "What is a service mesh?",
      "Explain the actor model in concurrency",
      "What is a bloom filter?",
      "Define memoization in computer science",
      "What is a quorum in distributed systems?",
      "Explain the two-phase commit protocol",
      "What is a hypervisor?",
      "Define idempotency in REST APIs",
      "What is a directed acyclic graph?",
      "Explain the difference between TCP and UDP",
      "What is a semaphore in operating systems?",
      "Define the observer pattern",
      "What is tail call optimization?",
      "Explain copy-on-write semantics",
      "What is a phantom type in Rust?",
    ],
  },
  {
    category: "quotations",
    mockKeyword: "mock:quotation",
    cssClass: ".typed-quotation",
    contentSelector: ".typed-quote-author",
    contentMatch: "Abelson",
    prompts: [
      "Famous quotes about programming",
      "Inspirational quotes from computer scientists",
      "What did Knuth say about premature optimization?",
      "Quotes about simplicity in software design",
      "Famous sayings about debugging code",
      "Quotes about the future of computing",
      "What did Dijkstra say about testing?",
      "Inspirational quotes about open source",
      "Famous quotes about cryptography",
      "What did Linus say about open development?",
      "Quotes about privacy and surveillance",
      "Famous sayings about programming languages",
      "What did Feynman say about understanding?",
      "Quotes about the art of writing code",
      "Famous sayings about Unix philosophy",
      "Quotes about software engineering discipline",
      "What did Brooks say about adding people to projects?",
      "Inspirational quotes about learning to code",
      "Famous quotes about artificial intelligence",
      "What did McCarthy say about Lisp?",
      "Quotes about the importance of tests",
      "Famous sayings about system architecture",
      "What did Ritchie say about C?",
      "Quotes about the web and its future",
      "Famous sayings about developer productivity",
    ],
  },
  {
    category: "flight reservations",
    mockKeyword: "mock:flightreservation",
    cssClass: ".canvas-block",
    contentSelector: ".block-content",
    contentMatch: "",
    prompts: [
      "Book a flight from SFO to JFK next Tuesday",
      "Find cheap flights to London in July",
      "Round trip flights from NYC to Tokyo under $800",
      "Direct flights from Austin to Seattle",
      "Best airlines for transatlantic travel",
      "Red-eye flights from Los Angeles to Miami",
      "Business class flights within Europe",
      "Compare flight prices for Thanksgiving travel",
      "Flights with the most legroom economy class",
      "Budget airlines that fly to Caribbean islands",
      "Connecting flights through Chicago O'Hare",
      "Flight options from Denver to New Orleans",
      "Flights with early morning departures from Boston",
      "Long haul flights with best in-flight WiFi",
      "Airline miles programs comparison",
      "Flights from Dallas to Vancouver Canada",
      "Last minute flight deals for weekend trips",
      "Flights near major holidays with price trends",
      "International flights with checked bag included",
      "Flights for solo travelers with good safety records",
      "Airlines that allow pet carry-on in cabin",
      "Flights from smaller regional airports",
      "Stopover options that allow city exploration",
      "Flights operated by code share partners",
      "First class upgrade options using points",
    ],
  },
  {
    category: "hotels",
    mockKeyword: "mock:hotel",
    cssClass: ".canvas-block",
    contentSelector: ".block-content",
    contentMatch: "",
    prompts: [
      "Hotels near the Eiffel Tower under $200/night",
      "Boutique hotels in New Orleans French Quarter",
      "Best hotels in Tokyo for first time visitors",
      "Eco-friendly hotels in Costa Rica",
      "Hotels with rooftop pools in Las Vegas",
      "Business hotels near San Francisco airport",
      "Budget hostels in Amsterdam with private rooms",
      "Luxury resorts in Maldives all-inclusive",
      "Historic hotels in Washington DC",
      "Pet-friendly hotels in Portland Oregon",
      "Hotels with best breakfast in Rome",
      "Waterfront hotels in Seattle downtown",
      "Extended stay hotels for remote workers",
      "Hotels with EV charging stations",
      "Ski-in ski-out hotels in Colorado",
      "Hotels near convention center in Chicago",
      "Beach resorts in Cancun family-friendly",
      "Boutique design hotels in Barcelona",
      "Hotels with spas in Sedona Arizona",
      "Capsule hotels in Japan for solo travel",
      "Hotels near national parks in Utah",
      "Airbnb alternatives for long term stays",
      "Hotels with free airport shuttle service",
      "Sustainable hotels with carbon offsets",
      "Hotels that support local communities",
    ],
  },
  {
    category: "recipes",
    mockKeyword: "mock:recipe",
    cssClass: ".canvas-block",
    contentSelector: ".block-content",
    contentMatch: "",
    prompts: [
      "Easy homemade bread recipe without a bread machine",
      "Vegetarian pasta recipes for weeknight dinners",
      "Traditional Italian carbonara recipe",
      "Gluten-free chocolate cake from scratch",
      "Quick 30-minute chicken stir fry recipe",
      "Authentic Thai green curry paste recipe",
      "Vegan mac and cheese that kids will love",
      "Japanese ramen from scratch recipe",
      "Sourdough starter and first loaf recipe",
      "Low-carb keto dinner recipes",
      "French onion soup authentic recipe",
      "Homemade pizza dough that tastes like restaurant",
      "Vegetable biryani recipe for dinner party",
      "Korean kimchi fried rice recipe",
      "Classic beef stew recipe for cold weather",
      "Butternut squash soup creamy recipe",
      "Shakshuka eggs in tomato sauce recipe",
      "Mango sticky rice Thai dessert recipe",
      "Chicken tikka masala from scratch",
      "Breakfast burritos meal prep recipe",
      "Banana bread with sourdough discard",
      "Greek moussaka authentic recipe",
      "Black bean tacos with chipotle sauce",
      "Lemon risotto with shrimp recipe",
      "Homemade granola with nuts and dried fruit",
    ],
  },
  {
    category: "software applications",
    mockKeyword: "mock:softwareapp",
    cssClass: ".canvas-block",
    contentSelector: ".block-content",
    contentMatch: "",
    prompts: [
      "Best code editors for Rust development",
      "Alternative to VSCode for Linux",
      "Password managers that are open source",
      "Note-taking apps that sync offline",
      "Best terminal emulators for macOS",
      "Video editing software under $100",
      "Open source alternatives to Adobe Photoshop",
      "Best email clients that respect privacy",
      "Database GUI tools for PostgreSQL",
      "API testing tools like Postman alternatives",
      "Screen recording software for tutorials",
      "Best diff tools for code review",
      "Open source project management tools",
      "CLI tools for working with JSON",
      "Best VPN software that does not log",
      "Markdown editors with live preview",
      "Static site generators for developers",
      "Browser extensions for productivity",
      "Best backup software for Linux",
      "Open source password managers",
      "RSS feed readers that work offline",
      "Best SQL query builders for beginners",
      "Container management GUI tools",
      "Offline maps applications for travel",
      "Best audio editing software free",
    ],
  },
  {
    category: "how-to guides",
    mockKeyword: "mock:howto",
    cssClass: ".canvas-block",
    contentSelector: ".block-content",
    contentMatch: "",
    prompts: [
      "How to set up a Rust development environment",
      "How to configure Vim for Rust development",
      "How to deploy a static site to GitHub Pages",
      "How to set up SSH key authentication",
      "How to containerize a Rust application with Docker",
      "How to configure Git for multiple accounts",
      "How to set up a local PostgreSQL database",
      "How to create a self-signed TLS certificate",
      "How to set up WireGuard VPN",
      "How to configure GitHub Actions for CI",
      "How to set up a Raspberry Pi as home server",
      "How to migrate from Bash to Zsh",
      "How to configure Nginx as a reverse proxy",
      "How to set up end-to-end encryption for email",
      "How to back up Linux home directory to S3",
      "How to configure fail2ban for SSH protection",
      "How to set up Prometheus and Grafana monitoring",
      "How to create a GPG key and sign commits",
      "How to set up a Tailscale mesh network",
      "How to configure systemd services",
      "How to set up Neovim from scratch",
      "How to use tmux for terminal multiplexing",
      "How to configure DNS with Cloudflare",
      "How to set up local development with HTTPS",
      "How to profile Rust code with perf",
    ],
  },
] as const;

// ── Test runner ───────────────────────────────────────────────

for (const cat of PROMPT_CATEGORIES) {
  test.describe(`Prompt category: ${cat.category}`, () => {
    // Mock-keyword route: guaranteed typed block render
    test(`renders typed block for ${cat.category}`, async ({ page }) => {
      const errors: string[] = [];
      page.on("pageerror", (e) => errors.push(e.message));

      await page.goto("/", { waitUntil: "commit" });
      await waitForApp(page);
      await submitPrompt(page, cat.mockKeyword);

      await expect(page.locator(cat.cssClass).first()).toBeVisible({ timeout: 15_000 });
      if (cat.contentMatch) {
        await expect(page.locator(cat.contentSelector).first()).toContainText(cat.contentMatch, {
          timeout: 5_000,
        });
      }

      const real = errors.filter(
        (e) =>
          !e.includes("disposed") && !e.includes("unreachable") && !e.includes("integrity")
      );
      expect(real).toHaveLength(0);
    });

    // 5 natural-language prompts per category: verify submit pipeline
    for (let i = 0; i < 5; i++) {
      const prompt = cat.prompts[i];
      test(`natural prompt [${i + 1}]: "${prompt.slice(0, 60)}"`, async ({ page }) => {
        const errors: string[] = [];
        page.on("pageerror", (e) => errors.push(e.message));

        await page.goto("/", { waitUntil: "commit" });
        await waitForApp(page);
        await submitPrompt(page, prompt);

        // Any canvas block means the submit pipeline fired
        await expect(page.locator(".canvas-block").first()).toBeVisible({ timeout: 15_000 });

        const real = errors.filter(
          (e) =>
            !e.includes("disposed") && !e.includes("unreachable") && !e.includes("integrity")
        );
        expect(real).toHaveLength(0);
      });
    }
  });
}
